FROM node:16.14.2-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:prod


FROM nginx:1.21.6-alpine
# RUN apk add --no-cache openssl
RUN mkdir -p /etc/nginx/ssl
COPY nginx/localhost-cert.pem nginx/localhost-key.pem /etc/nginx/ssl/
COPY nginx/nginx-https-localhost.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/editor-web-app /usr/share/nginx/html
EXPOSE 80 443
